test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,11 +10,7 @@ jobs:
       shell: cmd
       run: |
         set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%USERPROFILE%\Miniconda3;%USERPROFILE%\Miniconda3\Scripts;%PATH%
-        dotnet new tool-manifest
-        dotnet tool install Cake.Tool --version 4.0.0
-    - name: build
-      shell: pwsh
-      run: ./build.ps1
+        where msbuild || echo "msbuild not found"
     - name: test
       shell: cmd
       run: |
